# Generated by Django 3.1.1 on 2020-09-29 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppUser', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
    ]
