# Generated by Django 3.1.1 on 2020-09-29 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppUser', '0003_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_permissions',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
